//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStockLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public long ID { get; set; }
        public string Number { get; set; }
        public Nullable<long> TotalQuantityRequested { get; set; }
        public Nullable<long> TotalQuantityApproved { get; set; }
        public string Status { get; set; }
        public Nullable<long> OrderBranch { get; set; }
        public Nullable<long> OrderedBy { get; set; }
        public Nullable<System.DateTime> OrderdOn { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<long> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<long> DeclinedBy { get; set; }
        public Nullable<System.DateTime> DeclinedOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
