//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStockLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
            this.Orders3 = new HashSet<Order>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductCategories1 = new HashSet<ProductCategory>();
        }
    
        public long ID { get; set; }
        public string Lastname { get; set; }
        public string Othernames { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public Nullable<long> UserRole { get; set; }
        public string HashedPassword { get; set; }
        public Nullable<long> UserBranch { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> FirstTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Order> Orders2 { get; set; }
        public virtual ICollection<Order> Orders3 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories1 { get; set; }
        public virtual Role Role { get; set; }
    }
}
